apiVersion: v1
kind: ServiceAccount
metadata:
  name: aircargo-sa
  namespace: aircargo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aircargo-role
  namespace: aircargo
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aircargo-rolebinding
  namespace: aircargo
subjects:
  - kind: ServiceAccount
    name: aircargo-sa
    namespace: aircargo
roleRef:
  kind: Role
  name: aircargo-role
  apiGroup: rbac.authorization.k8s.io